# Generated by Django 2.1 on 2018-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='姓名', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='联系地址', max_length=255)),
                ('leave_msg', models.CharField(default='留言', max_length=1000)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
