# Generated by Django 2.1 on 2018-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteinfo',
            options={'verbose_name': '用户留言信息'},
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='leave_msg',
            field=models.CharField(max_length=1000, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='noteinfo',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
